apiVersion: v1
kind: Service
metadata:
  name: backend-api-service # Name of the Service
spec:
  selector:
    app: my-backend-api # Selects Pods with this label
  ports:
    - protocol: TCP
      port: 80 # Port exposed by the Service
      targetPort: 8080 # Port your container listens to (from your ReplicaSet)
  type: ClusterIP # Internal access only (default)


  
