apiVersion: v1
kind: Pod
metadata:
  name: ice-cream-pod
  labels:
    name: ice-cream-pod
    app: ice-cream-app
spec:
  containers:
    - name: ice-cream-app
      image: ghcr.io/jasmininnaka24/project-simulation-pipeline-container:latest
      port:
        - containerPort: 80
