apiVersion: v1
kind: Service
metadata:
  name: ice-cream-service
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30080 # Optional: specify a custom nodePort
  selector:
    app: ice-cream-app
  type: NodePort
