apiVersion: v1
kind: Pod
metadata:
  name: ice-cream-pod
  labels:
    app: ice-cream-app
spec:
  nodeSelector:
    kubernetes.io/role: worker
  containers:
    - name: ice-cream-app
      image: ghcr.io/jasmininnaka24/project-simulation-pipeline-container:latest
      ports:
        - containerPort: 80
