apiVersion: v1
kind: Service
metadata:
  name: ice-cream-service
spec:
  ports:
    - port: 80
      targetPort: 80 # Match the container port
      protocol: TCP
  selector:
    app: ice-cream-app
  type: LoadBalancer
